name: Release Pipeline to QA/DevM/UAT/Prod

on:
  workflow_dispatch:  # Enables manual triggering and allows user input
    inputs:
      solution_name:
        description: 'Name of the Power Platform solution to release'
        required: true
        default: 'ALI_G1'  # Default solution name, can be changed

permissions:
  contents: write

jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      # Use the dynamically provided solution name from workflow dispatch input
      solution_name: ${{ github.event.inputs.solution_name }}
      
      # Update your environment URLs here
      BUILD_ENVIRONMENT_URL: https://dev-aliii.crm.dynamics.com/  #qa
      QA_ENVIRONMENT_URL: https://dvm-aliii.crm.dynamics.com/
      UAT_ENVIRONMENT_URL: https://qa-aliii.crm.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://prod-aliii.crm.dynamics.com/
      
      CLIENT_ID: c9bfe35c-4011-4cea-a0b0-1d9aeb92158d
      TENANT_ID: cf98c142-3126-40f8-be8d-bef563a8f7a5      
    secrets:
      envSecret: ${{ secrets.SECRET_ID }}
